[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[font]
size = 16

[font.bold]
family = "Inconsolata Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Inconsolata Nerd Font Mono"

[font.normal]
family = "Inconsolata Nerd Font Mono"

[font.offset]
y = 4

[terminal.shell]
args = ["-l", "-c", "source ~/.zshrc; tmux attach || tmux"]
program = "/bin/zsh"

[window.dimensions]
columns = 256
lines = 64

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "None"

[terminal]
